### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by andrew-vant** [saltstack-formulas/rsyslog-formula#9]
We have a need to send logs over an untrusted network, and as far as I can tell the rsyslog formula doesn't have support for TLS. In the ubuntu world it's added using the rsyslog-gnutls package; I'm not sure about RHEL/cent.

I'm working on adding it in a fork, but thought I would file an issue in case someone already knows a good way to handle this.

**Comment by daks** [comment]
Hello,
we have the same need, is there any work done on this?
Thanks.
